//
//  Just.swift
//  Just
//
//  Created by Wirawit Rueopas.
//  Copyright © 2018 Wirawit Rueopas. All rights reserved.
//

import Foundation

/// Just request.
public struct Just {
    
    /**
     Make a request.
     
     - parameter url: URL
     - parameter method: HTTP Method. Either `.get` or `.post`
     - parameter parameters: `.get` -> queryString, `.post` -> either json body or url encoded
     - parameter headers: HTTP Headers
     - parameter configurationBlock: Configure the URLRequest generated by Just. *Don't forget to return the modified URLRequest.*
     - returns: Request object.
     */
    public static func request(_ url: URL, method: HTTPMethod, parameters: Parameters?=nil, headers: HTTPHeaders?=nil, configurationBlock: URLRequestConfigurationBlock?=nil) -> Request {
        return Request(url: url, method: method, parameters: parameters, headers: headers, configurationBlock: configurationBlock)
    }
    
    /**
     Make `GET` request. Return nil if the urlString is invalid.
     
     - parameter urlString: Url as String
     - parameter queries: Queries to be used in GET request
     - parameter headers: HTTP Headers
     - parameter configurationBlock: Configure the URLRequest generated by Just. *Don't forget to return the modified URLRequest.*
     - returns: Request object.
     */
    public static func get(_ urlString: String, queries: Parameters?=nil, headers: HTTPHeaders?=nil, configurationBlock: URLRequestConfigurationBlock?=nil) -> Request? {
        guard let url = URL(string: urlString) else { return nil }
        return Request(url: url, method: .get, parameters: queries, headers: headers, configurationBlock: configurationBlock)
    }
    
    /**
     Make `POST` request. Return nil if the urlString is invalid.
     
     - parameter urlString: Url as String
     - parameter body: body to be used in POST request
     - parameter encoding: Encoding for POST body (`.json` or `.url`)
     - parameter headers: HTTP Headers
     - parameter configurationBlock: Configure the URLRequest generated by Just. *Don't forget to return the modified URLRequest.*
     - returns: Request object.
     */
    public static func post(_ urlString: String, body: Parameters?=nil, encoding: POSTBodyEncoding, headers: HTTPHeaders?=nil, configurationBlock: URLRequestConfigurationBlock?=nil) -> Request? {
        guard let url = URL(string: urlString) else { return nil }
        return Request(url: url, method: .post(encoding), parameters: body, headers: headers, configurationBlock: configurationBlock)
    }
}
